language: python
sudo: false
python:
  - '3.8'
  - '3.7'
  - '3.6'
  - '3.5'
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=rinse setup.py test
after_success:
  - coveralls
